# Generated by Django 6.0 on 2026-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
