# Generated by Django 6.0 on 2026-01-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_rolemodel_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
