# Generated by Django 6.0 on 2025-12-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
