# Generated by Django 6.0 on 2025-12-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phonenumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
