# Generated by Django 6.0 on 2026-01-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usermodel_is_active_usermodel_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
