# Generated by Django 6.0 on 2025-12-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usermodel_email_alter_usermodel_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendinUserModel',
            fields=[
                ('user_id', models.CharField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phonenumber', models.CharField(blank=True, null=True, unique=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('expires_at', models.DateTimeField()),
                ('resent_count', models.IntegerField(default=0)),
                ('last_resent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
