# Generated by Django 6.0 on 2026-01-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_usermodel_user_id_alter_usermodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_permissions',
        ),
    ]
