# Generated by Django 6.0 on 2025-12-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pendinusermodel_alter_usermodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phonenumber', models.CharField(blank=True, null=True, unique=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('expires_at', models.DateTimeField()),
                ('resent_count', models.IntegerField(default=0)),
                ('last_resent_at', models.DateTimeField(blank=True, null=True)),
                ('validation_purpose', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='PendinUserModel',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phonenumber_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
