# Generated by Django 6.0 on 2026-01-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usermodel_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
