# Generated by Django 6.0 on 2025-12-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_verificationusermodel_delete_pendinusermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
