# Generated by Django 6.0 on 2025-12-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usermodel_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationusermodel',
            old_name='validation_purpose',
            new_name='verification_purpose',
        ),
    ]
