# Generated by Django 6.0 on 2025-12-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_validation_purpose_verificationusermodel_verification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
