# Generated by Django 6.0 on 2025-12-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usermodel_email_alter_usermodel_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_id',
            new_name='id',
        ),
    ]
