# Generated by Django 6.0 on 2025-12-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_user_id_usermodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationUserModel',
        ),
    ]
