# Generated by Django 6.0 on 2025-12-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_verificationusermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phonenumber_verified',
        ),
    ]
