# Generated by Django 6.0 on 2026-01-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='workspaces.workspacemembermodel'),
        ),
    ]
