# Generated by Django 6.0 on 2026-01-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskmodel_assigned_to'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_due',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workspaces.workspacemodel')),
            ],
            options={
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.stagemodel'),
        ),
        migrations.DeleteModel(
            name='StatusModel',
        ),
    ]
