# Generated by Django 6.0 on 2026-01-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_taskmodel_status_taskmodel_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='is_due',
            field=models.BooleanField(default=True),
        ),
    ]
